import { Roboto_Flex as Font, Roboto_Mono as MonoFont } from "next/font/google";
import Image from "next/image";
import clsx from "clsx";
import Link from "next/link";
import "./globals.css";

const regularFont = Font({
  subsets: ["latin"],
  variable: "--next-font",
});

const monoFont = MonoFont({
  subsets: ["latin"],
  variable: "--next-mono-font",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getCurrentAge = () => {
  const birthTimestamp = +new Date("01-14-1994");
  const currentTimestamp = +new Date();
  return (
    new Date(currentTimestamp - birthTimestamp).getUTCFullYear() -
    new Date(0).getUTCFullYear()
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          regularFont.variable,
          monoFont.variable,
          "flex w-[clamp(45ch,50%,75ch)] mx-auto py-16 items-center gap-8 tracking-wide bg-neutral-900 text-yellow-50"
        )}
      >
        <aside className="grid gap-4">
          <Image
            src="/avatar.png"
            alt="xandjiji's avatar"
            width={190}
            height={190}
            priority
            className="rounded sepia-[0.3]"
          />
          <div>
            <h2 className="font-bold text-[50px] leading-none tracking-wider">
              xandjiji
            </h2>
            <p className="font-light opacity-75">alexandre regali seleghim</p>
          </div>

          <div>
            <p>
              <a href="https://www.ifood.com.br/" target="_blank">
                @iFood
              </a>
            </p>
            <p>
              <a href="https://www.exevopan.com/">@exevopan</a>
            </p>
          </div>
        </aside>
        <header>
          <nav>
            <ul>
              <li>
                <Link href="/">README.md</Link>
              </li>
              <li>
                <Link href="/showcase">Showcase</Link>
              </li>
              <li>
                <Link href="/last-commits">Last commits</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
