import { Roboto_Flex as Font } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const font = Font({
  subsets: ["latin"],
  variable: "--next-font",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <header>
          <nav>
            <ul>
              <li>
                <Link href="/">README.md</Link>
              </li>
              <li>
                <Link href="/showcase">Showcase</Link>
              </li>
              <li>
                <Link href="/last-commits">Last commits</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
