import { Roboto_Flex as Font } from "next/font/google";
import { Header } from "@/components/header";
import "./globals.css";

const font = Font({
  subsets: ["latin"],
  variable: "--next-font",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
